---
- hosts: all
  tags: [db,web]
  tasks:
    - name: Group by EC2 type tag
      group_by: key={{ ec2_tag_type }}servers
      changed_when: false

- hosts: webservers
  tags: web
  sudo:  true
  tasks:
    - name: Ensure required packages are installed
      yum:  name={{ item }} state=present
      with_items:
        - httpd
        - python26-pip
        - git

    - name: Ensure our Python dependencies are installed
      pip: name={{ item }}
      with_items:
        - Flask
        - Flask-Bootstrap

    - name: Ensure our app parent path exists
      file: path=/srv/www state=directory
            owner=apache group=apache

    - name: Ensure our app is cloned
      git:  repo=https://github.com/phips/flask_app.git
            dest=/srv/www/flask_app
      when: install_app|default(False)

    - name: Ensure service definition is in place
      copy: src=files/app.init dest=/etc/init.d/doxlon
            mode=0755

    - name: Ensure our app is running
      service: name=doxlon pattern=app.py state=restarted enabled=true
      when: install_app|default(False)

    - name: Ensure Apache serves our app
      template: src=files/app.conf.j2 dest=/etc/httpd/conf.d/app.conf
      when: install_app|default(False)
      notify:
        - restart apache

    - name: Ensure Apache is running
      service: name=httpd state=running enabled=true

  handlers:
    - name: restart apache
      service: name=httpd state=restarted

- hosts: dbservers
  tags: db
  sudo:  true
  tasks:
    - name: Ensure database is installed
      yum: name=postgresql93-server state=present

    - name: Initialise the database
      command: service postgresql93 initdb
               creates=/var/lib/pgsql93/data/PG_VERSION

    - name: Ensure database is running
      service: name=postgresql93 state=running enabled=true

